---

- name: Install Postfix APT packages
  apt:
    name: '{{ item }}'
    state: 'present'
    install_recommends: False
  with_flattened:
    - '{{ postfix__base_packages }}'
  when: ansible_pkg_mgr == 'apt'

- name: Generate Postfix 'main.cf' configuration
  template:
    src: 'postfix/main.cf.j2'
    dest: '/etc/postfix/main.cf'
    owner: 'root'
    group: 'root'
    mode: '0644'
  notify: [ 'Check postfix and reload' ]

- name: Generate Postfix 'master.cf' configuration
  template:
    src: 'postfix/master.cf.j2'
    dest: '/etc/postfix/master.cf'
    owner: 'root'
    group: 'root'
    mode: '0644'
  notify: [ 'Check postfix and reload' ]

- name: Generate Postfix virtual alias maps configuration
  template:
    src: 'postfix/virtual-alias-maps.j2'
    dest: '/etc/postfix/virtual-alias-maps'
    owner: 'root'
    group: 'root'
    mode: '0644'
  notify: [ 'Regenerate Alias Maps' ]

- name: Generate Postfix virtual alias domains configuration
  template:
    src: 'postfix/virtual-alias-domains.j2'
    dest: '/etc/postfix/virtual-alias-domains'
    owner: 'root'
    group: 'root'
    mode: '0644'
  notify: [ 'Regenerate Domain Aliases' ]

- name: Generate 'alias maps' configuration
  template:
    src: 'postfix/alias.j2'
    dest: '/etc/postfix/alias'
    owner: 'root'
    group: 'root'
    mode: '0644'
  notify: [ 'Regenerate Aliases' ]  

- name: Enable postfix in UFW
  ufw:
    rule: allow
    name: Postfix

- name: Enable postfix systemd service
  systemd:
    name: postfix
    state: started
    enabled: True