---

- name: Check postfix and restart
  command: /usr/sbin/postfix -c /etc/postfix check
  notify: [ 'Restart postfix' ]

- name: Check postfix and reload
  command: /usr/sbin/postfix -c /etc/postfix check
  notify: [ 'Restart postfix' ]

- name: Restart postfix
  service:
    name: 'postfix'
    state: 'restarted'

- name: Reload postfix
  service:
    name: 'postfix'
    state: 'reloaded'

- name: Regenerate Aliases
  command: /usr/sbin/postalias /etc/postfix/alias 
  notify: [ 'Check postfix and restart' ] 

- name: Regenerate Domain Aliases
  command: /usr/sbin/postmap /etc/postfix/virtual-alias-domains
  notify: [ 'Check postfix and restart' ] 

- name: Regenerate Alias Maps
  command:  /usr/sbin/postmap  /etc/postfix/virtual-alias-maps
  notify: [ 'Check postfix and restart' ] 


